from .add_virtual_machine import AddVirtualMachineComposition
from .change_password import ChangeUserPasswordComposition
from .claim_virtual_machine import ClaimVirtualMachineComposition
from .free_virtual_machine import FreeVirtualMachineComposition
from .get_user import GetUserComposition
from .login_user import LoginUserComposition
from .register_user import RegisterUserComposition
from .update_user_activation_key import UpdateUserActivationKeyComposition
